apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-multiple-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongo-multiple-hpa
  namespace: default
spec:
  maxReplicas: 9
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongo-multiple
  targetCPUUtilizationPercentage: 50

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-multiple
spec:
  selector:
    matchLabels:
      app: mongo-multiple
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-multiple
    spec:
      containers:
        - name: mongo-multiple
          image: majeranowski/tech241-mongodb:v1
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage-multiple
              mountPath: /data/db
      volumes:
        - name: storage-multiple
          persistentVolumeClaim:
            claimName: mongo-multiple-db
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-multiple
spec:
  selector:
    app: mongo-multiple
  ports:
    - port: 27017
      targetPort: 27017