---
# select the type of API version and type of service
apiVersion: v1
kind: Service
#Metadata for name
metadata:
  name: node-svc
  namespace: default  # sre
# Specification to include ports Selector to connect to the deployment
spec:
  ports:
  - nodePort: 30002 # range is 30000 - 32768
    port: 3000
    targetPort: 3000

# Let's define the selector and label to connect to nginx deployment
  selector:
    app: node

  # Creating NodePort of deployment
  type: NodePort # alse use LoadBalancer - for local use ClasterIP